AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
    --------------------
    at Protocol._enqueue (/Users/hikmamuneer/Desktop/iOS/skyes_wardrobe_node/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/hikmamuneer/Desktop/iOS/skyes_wardrobe_node/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/Users/hikmamuneer/Desktop/iOS/skyes_wardrobe_node/node_modules/mysql/lib/Connection.js:116:18)
    at reconnect (/Users/hikmamuneer/Desktop/iOS/skyes_wardrobe_node/helpers/db_helpers.js:18:16)
    at Connection.<anonymous> (/Users/hikmamuneer/Desktop/iOS/skyes_wardrobe_node/helpers/db_helpers.js:54:13)
    at Connection.emit (node:events:514:28)
    at Connection._handleProtocolError (/Users/hikmamuneer/Desktop/iOS/skyes_wardrobe_node/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:514:28)
    at Protocol._delegateError (/Users/hikmamuneer/Desktop/iOS/skyes_wardrobe_node/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/Users/hikmamuneer/Desktop/iOS/skyes_wardrobe_node/node_modules/mysql/lib/protocol/Protocol.js:380:10)